"""
api/main.py — FastAPI Prediction Service
==========================================
Endpoints:
  GET  /          → health check + model info
  POST /predict   → takes JSON health data, returns risk level + confidence

Run locally:
  uvicorn api.main:app --reload --host 0.0.0.0 --port 8000

Interactive docs (auto-generated by FastAPI):
  http://127.0.0.1:8000/docs
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
from pathlib import Path

from fastapi             import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic            import BaseModel, Field, field_validator

# ── Load artifacts ────────────────────────────────────────────────────────────
# Resolve paths relative to this file (works regardless of working directory)
BASE_DIR = Path(__file__).resolve().parent.parent
MODELS_DIR = BASE_DIR / "models"


def _load(filename):
    path = MODELS_DIR / filename
    if not path.exists():
        raise FileNotFoundError(
            f"Model file not found: {path}\n"
            "Run src/02_preprocess_and_train.py first."
        )
    return joblib.load(path)


model        = _load("best_model.pkl")
num_imputer  = _load("num_imputer.pkl")
cat_imputer  = _load("cat_imputer.pkl")
scaler       = _load("scaler.pkl")

with open(MODELS_DIR / "metadata.json") as f:
    metadata = json.load(f)

NUMERIC_FEATURES     = metadata["numeric"]
CATEGORICAL_FEATURES = metadata["categorical"]
ALL_FEATURES         = metadata["features"]
LABEL_MAP            = {int(k): v for k, v in metadata["label_map"].items()}
# {0: "Low", 1: "Medium", 2: "High"}


# ── FastAPI app ───────────────────────────────────────────────────────────────
app = FastAPI(
    title="Smart Health Risk Predictor",
    description=(
        "Predicts a person's cardiovascular health risk level "
        "(Low / Medium / High) using a trained ML model."
    ),
    version="1.0.0",
)

# Allow requests from the frontend (localhost for dev, Netlify/Vercel for prod)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # restrict to your frontend domain in production
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# ── Input schema (Pydantic) ───────────────────────────────────────────────────
class HealthInput(BaseModel):
    """
    All 13 features from the UCI Heart Disease dataset.
    Pydantic validates types and ranges automatically — invalid input
    returns a clear 422 error with an explanation.
    """

    # Numeric features
    age:      float = Field(..., ge=1,  le=120, description="Age in years", example=52)
    trestbps: float = Field(..., ge=50, le=250, description="Resting blood pressure (mmHg)", example=125)
    chol:     float = Field(..., ge=50, le=700, description="Serum cholesterol (mg/dl)", example=212)
    thalach:  float = Field(..., ge=50, le=250, description="Maximum heart rate achieved", example=168)
    oldpeak:  float = Field(..., ge=0,  le=10,  description="ST depression induced by exercise", example=1.0)

    # Categorical features
    sex:     int = Field(..., ge=0, le=1,  description="Sex (0=Female, 1=Male)", example=0)
    cp:      int = Field(..., ge=0, le=3,  description="Chest pain type (0=Typical, 1=Atypical, 2=Non-anginal, 3=Asymptomatic)", example=2)
    fbs:     int = Field(..., ge=0, le=1,  description="Fasting blood sugar > 120 mg/dl (0=No, 1=Yes)", example=0)
    restecg: int = Field(..., ge=0, le=2,  description="Resting ECG results (0=Normal, 1=ST-T abnormality, 2=LV hypertrophy)", example=0)
    exang:   int = Field(..., ge=0, le=1,  description="Exercise-induced angina (0=No, 1=Yes)", example=0)
    slope:   int = Field(..., ge=0, le=2,  description="Slope of peak exercise ST segment (0=Upsloping, 1=Flat, 2=Downsloping)", example=2)
    ca:      int = Field(..., ge=0, le=4,  description="Number of major vessels coloured by fluoroscopy (0–3)", example=0)
    thal:    int = Field(..., ge=0, le=3,  description="Thalassemia (0=Normal, 1=Fixed defect, 2=Reversible defect, 3=Unknown)", example=2)

    @field_validator("ca", "thal")
    @classmethod
    def ca_thal_valid(cls, v):
        # These sometimes have NaN encoded as 0 in the raw dataset.
        # Values 0-3 are valid; 4 maps to "unknown" for ca.
        return v


# ── Output schema ─────────────────────────────────────────────────────────────
class PredictionOutput(BaseModel):
    risk_level:  str
    risk_code:   int
    confidence:  float
    probabilities: dict[str, float]
    model_name:  str


# ── Helper: run inference ─────────────────────────────────────────────────────
def run_inference(data: HealthInput) -> PredictionOutput:
    # Build a DataFrame with the correct column order
    row = {
        "age":     data.age,     "trestbps": data.trestbps,
        "chol":    data.chol,    "thalach":  data.thalach,
        "oldpeak": data.oldpeak, "sex":      data.sex,
        "cp":      data.cp,      "fbs":      data.fbs,
        "restecg": data.restecg, "exang":    data.exang,
        "slope":   data.slope,   "ca":       data.ca,
        "thal":    data.thal,
    }
    df = pd.DataFrame([row], columns=ALL_FEATURES)

    # Impute (handles any NaN)
    df[NUMERIC_FEATURES]     = num_imputer.transform(df[NUMERIC_FEATURES])
    df[CATEGORICAL_FEATURES] = cat_imputer.transform(df[CATEGORICAL_FEATURES])

    # Scale numeric features
    df[NUMERIC_FEATURES] = scaler.transform(df[NUMERIC_FEATURES])

    # Predict
    risk_code = int(model.predict(df)[0])
    proba     = model.predict_proba(df)[0]  # shape: (3,)

    probabilities = {
        LABEL_MAP[i]: round(float(p), 4)
        for i, p in enumerate(proba)
    }
    confidence = round(float(proba[risk_code]), 4)

    return PredictionOutput(
        risk_level    = LABEL_MAP[risk_code],
        risk_code     = risk_code,
        confidence    = confidence,
        probabilities = probabilities,
        model_name    = metadata["best_model"],
    )


# ── Routes ────────────────────────────────────────────────────────────────────
@app.get("/", summary="Health check")
def root():
    """Returns model info and confirms the API is running."""
    return {
        "status":     "ok",
        "model":      metadata["best_model"],
        "f1_macro":   metadata["metrics"].get("f1_macro_tuned", metadata["metrics"]["f1_macro"]),
        "classes":    list(LABEL_MAP.values()),
        "docs_url":   "/docs",
    }


@app.post("/predict", response_model=PredictionOutput, summary="Predict health risk")
def predict(data: HealthInput):
    """
    Takes 13 health parameters and returns:
    - risk_level:    'Low', 'Medium', or 'High'
    - confidence:    model's confidence in this prediction (0–1)
    - probabilities: per-class probabilities
    """
    try:
        return run_inference(data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# ── Example request (shown in docs) ──────────────────────────────────────────
# POST /predict
# {
#   "age": 52,  "sex": 0,  "cp": 2,   "trestbps": 125, "chol": 212,
#   "fbs": 0,   "restecg": 0, "thalach": 168, "exang": 0,
#   "oldpeak": 1.0, "slope": 2, "ca": 0, "thal": 2
# }
